version: '3.8'

services:

  mysql_fullstack:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql_data_1:/var/lib/mysql
    networks:
      - next_network

  app_next:
    image: asree001/booking-app-next:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://${MYSQL_USERNAME}:${MYSQL_PASSWORD}@mysql_fullstack:3306/${MYSQL_DATABASE}
    env_file:
      - .env
    depends_on:
      - mysql_fullstack
    networks:
      - next_network

volumes:
  mysql_data_1:
  caddy_data:
  caddy_config:

networks:
  next_network:
    driver: bridge