version: '3.8'

services:
  mysql_fullstack:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    env_file:
      - .env
    # env_file:
    #   - .env.prod
    volumes:
      - mysql_data_1:/var/lib/mysql

volumes:
  mysql_data_1:
